scan_orphans:
  name: Scan for Orphaned Entities
  description: Scan the entity registry for orphaned entities
  fields: {}

clean_orphans:
  name: Clean Orphaned Entities
  description: Remove orphaned entities from the registry
  fields:
    entity_ids:
      name: Entity IDs
      description: Specific entities to clean (optional, defaults to all orphaned)
      required: false
      selector:
        entity:
          multiple: true
    dry_run:
      name: Dry Run
      description: Preview what would be cleaned without actually removing entities
      required: false
      default: true
      selector:
        boolean:
    backup_before_clean:
      name: Backup Before Clean
      description: Create a backup file before cleaning entities
      required: false
      default: true
      selector:
        boolean:

backup_entities:
  name: Backup Entities
  description: Create a backup of orphaned entities
  fields:
    entity_ids:
      name: Entity IDs
      description: Specific entities to backup (optional, defaults to all orphaned)
      required: false
      selector:
        entity:
          multiple: true

restore_entities:
  name: Restore Entities
  description: Restore entities from a backup file (not yet implemented)
  fields:
    backup_file:
      name: Backup File
      description: Path to the backup file to restore
      required: true
      selector:
        text:
